//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlybangiay.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        public string ID_Hinh { get; set; }
        public string ID_Giay { get; set; }
        public byte[] AnhSP { get; set; }
    
        public virtual Giay Giay { get; set; }
    }
}
