//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlybangiay.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string ID_HoaDon { get; set; }
        public string ID_KhuyenMai { get; set; }
        public string TenKhachHang { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string ID_NhanVien { get; set; }
    
        public virtual CTKM CTKM { get; set; }
        public virtual ChiTietHoaDon ChiTietHoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
