//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlybangiay.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapKho
    {
        public int Stt { get; set; }
        public string ID_Giay { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<System.DateTime> NhayNhap { get; set; }
    
        public virtual Kho Kho { get; set; }
    }
}
