//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlybangiay.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string Username { get; set; }
        public string Pass { get; set; }
        public Nullable<bool> ChucVu { get; set; }
        public string ID_NhanVien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
